
export const color = {
  primary: '#53B175',
  secondary: '#414757',
  error: '#f13a59',
  notBlack: '#181725',
  notGray: '#7C7C7C',
  gray: '#B3B3B3',
  notPink: '#FA8072',
  lineBorder: '#E2E2E2',
  darkGreen: '#013220',
  aqua: '#0FFFFF',
  yellowGreen: '#9acd32',
  oliveGreen: '#556b2f',
  activeGray: '#D1D1D1',
  lightYellow: '#FFE1A1',
  redBtn: '#FA3E1C',
  bottomBar: '#2D333B',
  lightGreyColor: 'rgba(0, 0, 0, 0.38)',

  //new palette
  mRed: '#DD4040',
  lRed: '#F15A5A',
  purple: '#955BA5',
  ocean: '#6387A6',
  sky: '#2D95BF',
  bronze: '#D9A441',
  yellow: '#F0C419',
  deep: '#4E6177',
  green: '#4EBA6F',
  dGrey: '#8C8C8C',
  mGrey: '#CCCCCC',
  grey: '#EEEEEE',
  lGrey: '#FAFAFA',
  mBlack: '#333333',
  lBlack: '#555555',
  pink: '#eb2f96',
  white: '#ffff',
};


export const size = {
  tiny: 8,
  small: 12,
  normal: 14,
  large: 18,
  largeX: 20,
  h1: 40,
  h2: 34,
  h3: 28,
  h4: 22,
  h5: 16,
  h6: 10,
  h7: 4,
};

export const fontFamily = {
  GilroyMedium: 'Gilroy-Medium',
  GilroyLight: 'Gilroy-Light',
  GilroyExtraBold: 'Gilroy-ExtraBold',
  GilroySemiBold: 'Gilroy-SemiBold',
  Quicksand: 'Quicksand',
  QuicksandBold: 'Quicksand-Bold',
  QuicksandMedium: 'Quicksand-Medium',
  QuicksandSemiBold: 'Quicksand-SemiBold',
  CabinBold: 'Cabin-Bold',
  CabinRegular: 'Cabin-Regular',
  CabinSemiBold: 'Cabin-SemiBold',
  Cabin: 'Cabin',
  ComfortaaBold: 'Comfortaa-Bold',
  ComfortaaMedium: 'Comfortaa-Medium',
  Comfortaa: 'Comfortaa',
  FiraSansExtraLight: 'FiraSans-ExtraLight',
  FiraSansMedium: 'FiraSansMedium',
  RobotoBold: 'Roboto-Bold',
  RobotoLight: 'Roboto-Light',
  RobotoMedium: 'Roboto-Medium',
  SourceSansProLight: 'SourceSansPro-Light',
  SourceSansProRegular: 'SourceSansProRegular',
  SourceSansProSemiBold: 'SourceSansProSemiBold',
};

export const fontWeight = {
   odd1: '100',
  even2: '200',
  odd3: '300',
  even4: '400',
  odd5: '500',
  even6: '600',
  odd7: '700',
  even8: '800',
  odd9: '900',
};
