export const constants = {
  COLOR: {
    PRIMARY: '#53B175',
    SECONDARY: '#414757',
    Price:'#FE724C',
    item:'#252121'
  },
  FONT: {
    GilroyMedium: 'Gilroy-Medium',
    GilroyLight: 'Gilroy-Light',
    GilroyExtraBold: 'Gilroy-ExtraBold',
    GilroySemiBold: 'Gilroy-SemiBold',
    Quicksand: 'Quicksand',
    QuicksandBold: 'Quicksand-Bold',
    QuicksandMedium: 'Quicksand-Medium',
    QuicksandSemiBold: 'Quicksand-SemiBold',
    CabinBold: 'Cabin-Bold',
    CabinRegular: 'Cabin-Regular',
    CabinSemiBold: 'Cabin-SemiBold',
    Cabin: 'Cabin',
    ComfortaaBold: 'Comfortaa-Bold',
    ComfortaaMedium: 'Comfortaa-Medium',
    Comfortaa: 'Comfortaa',
    FiraSansExtraLight: 'FiraSans-ExtraLight',
    FiraSansMedium: 'FiraSansMedium',
    RobotoBold: 'Roboto-Bold',
    RobotoLight: 'Roboto-Light',
    RobotoMedium: 'Roboto-Medium',
    SourceSansProLight: 'SourceSansPro-Light',
    SourceSansProRegular: 'SourceSansProRegular',
    SourceSansProSemiBold: 'SourceSansProSemiBold',
  },
  BASE_URL: {
    MAIN: 'http://localhost:3000/api',
    SECOND: 'https://fpoly-hcm.herokuapp.com/api',
    THIRD: 'https://cumtumdim.becofoodstore.click/api',
  },
};
