export const constants = {
  COLOR: {
    PRIMARY: '#252121',
    ORANGE: '#FE724C',
    GREY: '#252121',
    YELLOW: '#FFB703',
    BLACK: '#282222',
    WHITE: '#FFFFFF',
    RED: '#F20000',
    DARK_BROWN: '#2F2D2D',
  },
  FONT: {
    GilroyMedium: 'Gilroy-Medium',
    GilroyLight: 'Gilroy-Light',
    GilroyExtraBold: 'Gilroy-ExtraBold',
    GilroySemiBold: 'Gilroy-SemiBold',
    Quicksand: 'Quicksand',
    QuicksandBold: 'Quicksand-Bold',
    QuicksandMedium: 'Quicksand-Medium',
    QuicksandSemiBold: 'Quicksand-SemiBold',
    CabinBold: 'Cabin-Bold',
    CabinRegular: 'Cabin-Regular',
    CabinSemiBold: 'Cabin-SemiBold',
    Cabin: 'Cabin',
    ComfortaaBold: 'Comfortaa-Bold',
    ComfortaaMedium: 'Comfortaa-Medium',
    Comfortaa: 'Comfortaa',
    FiraSansExtraLight: 'FiraSans-ExtraLight',
    FiraSansMedium: 'FiraSansMedium',
    RobotoBold: 'Roboto-Bold',
    RobotoLight: 'Roboto-Light',
    RobotoMedium: 'Roboto-Medium',
    SourceSansProLight: 'SourceSansPro-Light',
    SourceSansProRegular: 'SourceSansProRegular',
    SourceSansProSemiBold: 'SourceSansProSemiBold',
  },
  BASE_URL: {
    MAIN: 'http://192.168.1.155:3000/api',
    SECOND: 'https://fpoly-hcm.herokuapp.com/api',
    THIRD: 'https://cumtumdim.becofoodstore.click/api',
  },
  ROLE: {
    ADMIN: 'admin',
    USER: 'user',
  },
  GOOGLE_CONSOLE: {
    WEB_CLIENT:
      '8392071542-uket243u20vj719uir2iu1ofh4chq7oc.apps.googleusercontent.com',
    IOS_CLIENT:
      '8392071542-6jau34qpcu594et1vbt2uukakso783au.apps.googleusercontent.com',
    ANDROID_CLIENT:
      '8392071542-rhodj3pj05jsqjer7661m8d1pprerrio.apps.googleusercontent.com',
  },
  SCOPES: {
    PROFILE: 'profile',
    EMAIL: 'email',
  },
  FETCH: {
    LOGIN: 'fetchLogin',
    UPLOAD_IMAGE: 'fetchUploadImage',
    SIGN_OUT: 'fetchSignOut',
    FIND_CATEGORIES: 'fetchCategories',
    ADD_DISH: 'fetchAddDish',
  },
  SLICE: {
    ADMIN: 'admin',
    AUTH: 'auth',
    PRODUCT: 'product',
  },
};
